spring:
  application:
    name: microservice2

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      
server:
  servlet:
    context-path: /microservice2
  port: 8081

com:
  amazonaws:
    xray:
      metrics:
        daemonAddress: localhost:2000

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80
