server:
  servlet:
    context-path: /microservice2
  port: 8081

com:
  amazonaws:
    xray:
      metrics:
        daemonAddress: localhost:2000

---

spring:
  config:
    activate:
      on-profile: dev

server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80
