---

apiVersion: v1
kind: Service
metadata:
  name: microservice1
  labels:
    run: microservice1
spec:
  ports:
    - name: prometheus
      port: 80
      protocol: TCP
  selector:
    run: microservice1
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: microservice1
spec:
  serviceName: microservice1
  selector:
    matchLabels:
      run: microservice1
  replicas: 1
  template:
    metadata:
      labels:
        run: microservice1
    spec:
      containers:
        - name: microservice1
          image: microservice1:0.0.1-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: IS_STATEFUL_SET
              value: "1"
            - name: API_CNAME
              value: microservice1.default
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: xray-service.default:2000
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-microservice1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /microservice1/$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /microservice1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: microservice1
                port:
                  number: 80