spring:
  application:
    name: microservice1
  profiles:
    include:
      endpoints

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

sjd:
  greeting: Greetings
  env-name: steve

server:
  servlet:
    context-path: /microservice1
  port: 8080

com:
  amazonaws:
    xray:
      metrics:
        daemonAddress: localhost:2000

---

spring:
  config:
    activate:
      on-profile: dev

sjd:
  env-name: steve-dev

server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: prod

sjd:
  env-name: steve-prod

server:
  port: 80
